version: 2

models:
    - name: dim_customer
      description: "model"
    
    - name: fct_orders
      description: "sum finding from customer"
    - name: int_orders_pivoted
      description: "amount gained"


